class Country {
  final String name;
  final String code;
  final String flag;
  final int maxLength;

  const Country({
    required this.name,
    required this.code,
    required this.flag,
    this.maxLength = 10,
  });
}

const List<Country> countries = [
  Country(name: "Afghanistan", code: "+93", flag: "🇦🇫", maxLength: 9),
  Country(name: "Albania", code: "+355", flag: "🇦🇱", maxLength: 9),
  Country(name: "Algeria", code: "+213", flag: "🇩🇿", maxLength: 9),
  Country(name: "Andorra", code: "+376", flag: "🇦🇩", maxLength: 6),
  Country(name: "Angola", code: "+244", flag: "🇦🇴", maxLength: 9),
  Country(name: "Argentina", code: "+54", flag: "🇦🇷", maxLength: 10),
  Country(name: "Armenia", code: "+374", flag: "🇦🇲", maxLength: 8),
  Country(name: "Australia", code: "+61", flag: "🇦🇺", maxLength: 9),
  Country(name: "Austria", code: "+43", flag: "🇦🇹", maxLength: 10),
  Country(name: "Azerbaijan", code: "+994", flag: "🇦🇿", maxLength: 9),
  Country(name: "Bahrain", code: "+973", flag: "🇧🇭", maxLength: 8),
  Country(name: "Bangladesh", code: "+880", flag: "🇧🇩", maxLength: 10),
  Country(name: "Belarus", code: "+375", flag: "🇧🇾", maxLength: 9),
  Country(name: "Belgium", code: "+32", flag: "🇧🇪", maxLength: 9),
  Country(name: "Benin", code: "+229", flag: "🇧🇯", maxLength: 8),
  Country(name: "Bhutan", code: "+975", flag: "🇧🇹", maxLength: 8),
  Country(name: "Bolivia", code: "+591", flag: "🇧🇴", maxLength: 8),
  Country(name: "Bosnia and Herzegovina", code: "+387", flag: "🇧🇦", maxLength: 8),
  Country(name: "Botswana", code: "+267", flag: "🇧🇼", maxLength: 8),
  Country(name: "Brazil", code: "+55", flag: "🇧🇷", maxLength: 11),
  Country(name: "Bulgaria", code: "+359", flag: "🇧🇬", maxLength: 9),
  Country(name: "Burkina Faso", code: "+226", flag: "🇧🇫", maxLength: 8),
  Country(name: "Burundi", code: "+257", flag: "🇧🇮", maxLength: 8),
  Country(name: "Cambodia", code: "+855", flag: "🇰🇭", maxLength: 9),
  Country(name: "Cameroon", code: "+237", flag: "🇨🇲", maxLength: 9),
  Country(name: "Canada", code: "+1", flag: "🇨🇦", maxLength: 10),
  Country(name: "Central African Republic", code: "+236", flag: "🇨🇫", maxLength: 8),
  Country(name: "Chad", code: "+235", flag: "🇹🇩", maxLength: 8),
  Country(name: "Chile", code: "+56", flag: "🇨🇱", maxLength: 9),
  Country(name: "China", code: "+86", flag: "🇨🇳", maxLength: 11),
  Country(name: "Colombia", code: "+57", flag: "🇨🇴", maxLength: 10),
  Country(name: "Comoros", code: "+269", flag: "🇰🇲", maxLength: 7),
  Country(name: "Congo", code: "+242", flag: "🇨🇬", maxLength: 9),
  Country(name: "Costa Rica", code: "+506", flag: "🇨🇷", maxLength: 8),
  Country(name: "Croatia", code: "+385", flag: "🇭🇷", maxLength: 9),
  Country(name: "Cuba", code: "+53", flag: "🇨🇺", maxLength: 8),
  Country(name: "Cyprus", code: "+357", flag: "🇨🇾", maxLength: 8),
  Country(name: "Czech Republic", code: "+420", flag: "🇨🇿", maxLength: 9),
  Country(name: "Denmark", code: "+45", flag: "🇩🇰", maxLength: 8),
  Country(name: "Djibouti", code: "+253", flag: "🇩🇯", maxLength: 8),
  Country(name: "Dominica", code: "+1-767", flag: "🇩🇲", maxLength: 7),
  Country(name: "Dominican Republic", code: "+1-809", flag: "🇩🇴", maxLength: 7),
  Country(name: "Ecuador", code: "+593", flag: "🇪🇨", maxLength: 9),
  Country(name: "Egypt", code: "+20", flag: "🇪🇬", maxLength: 10),
  Country(name: "El Salvador", code: "+503", flag: "🇸🇻", maxLength: 8),
  Country(name: "Equatorial Guinea", code: "+240", flag: "🇬🇶", maxLength: 9),
  Country(name: "Eritrea", code: "+291", flag: "🇪🇷", maxLength: 7),
  Country(name: "Estonia", code: "+372", flag: "🇪🇪", maxLength: 8),
  Country(name: "Ethiopia", code: "+251", flag: "🇪🇹", maxLength: 9),
  Country(name: "Fiji", code: "+679", flag: "🇫🇯", maxLength: 7),
  Country(name: "Finland", code: "+358", flag: "🇫🇮", maxLength: 9),
  Country(name: "France", code: "+33", flag: "🇫🇷", maxLength: 9),
  Country(name: "Gabon", code: "+241", flag: "🇬🇦", maxLength: 7),
  Country(name: "Gambia", code: "+220", flag: "🇬🇲", maxLength: 7),
  Country(name: "Georgia", code: "+995", flag: "🇬🇪", maxLength: 9),
  Country(name: "Germany", code: "+49", flag: "🇩🇪", maxLength: 11),
  Country(name: "Ghana", code: "+233", flag: "🇬🇭", maxLength: 9),
  Country(name: "Greece", code: "+30", flag: "🇬🇷", maxLength: 10),
  Country(name: "Grenada", code: "+1-473", flag: "🇬🇩", maxLength: 7),
  Country(name: "Guatemala", code: "+502", flag: "🇬🇹", maxLength: 8),
  Country(name: "Guinea", code: "+224", flag: "🇬🇳", maxLength: 9),
  Country(name: "Guinea-Bissau", code: "+245", flag: "🇬🇼", maxLength: 7),
  Country(name: "Guyana", code: "+592", flag: "🇬🇾", maxLength: 7),
  Country(name: "Haiti", code: "+509", flag: "🇭🇹", maxLength: 8),
  Country(name: "Honduras", code: "+504", flag: "🇭🇳", maxLength: 8),
  Country(name: "Hungary", code: "+36", flag: "🇭🇺", maxLength: 9),
  Country(name: "Iceland", code: "+354", flag: "🇮🇸", maxLength: 7),
  Country(name: "India", code: "+91", flag: "🇮🇳", maxLength: 10),
  Country(name: "Indonesia", code: "+62", flag: "🇮🇩", maxLength: 11),
  Country(name: "Iran", code: "+98", flag: "🇮🇷", maxLength: 10),
  Country(name: "Iraq", code: "+964", flag: "🇮🇶", maxLength: 10),
  Country(name: "Ireland", code: "+353", flag: "🇮🇪", maxLength: 9),
  Country(name: "Israel", code: "+972", flag: "🇮🇱", maxLength: 9),
  Country(name: "Italy", code: "+39", flag: "🇮🇹", maxLength: 10),
  Country(name: "Ivory Coast", code: "+225", flag: "🇨🇮", maxLength: 8),
  Country(name: "Jamaica", code: "+1-876", flag: "🇯🇲", maxLength: 7),
  Country(name: "Japan", code: "+81", flag: "🇯🇵", maxLength: 10),
  Country(name: "Jordan", code: "+962", flag: "🇯🇴", maxLength: 9),
  Country(name: "Kazakhstan", code: "+7", flag: "🇰🇿", maxLength: 10),
  Country(name: "Kenya", code: "+254", flag: "🇰🇪", maxLength: 9),
  Country(name: "Kiribati", code: "+686", flag: "🇰🇮", maxLength: 8),
  Country(name: "Kuwait", code: "+965", flag: "🇰🇼", maxLength: 8),
  Country(name: "Kyrgyzstan", code: "+996", flag: "🇰🇬", maxLength: 9),
  Country(name: "Laos", code: "+856", flag: "🇱🇦", maxLength: 9),
  Country(name: "Latvia", code: "+371", flag: "🇱🇻", maxLength: 8),
  Country(name: "Lebanon", code: "+961", flag: "🇱🇧", maxLength: 8),
  Country(name: "Lesotho", code: "+266", flag: "🇱🇸", maxLength: 8),
  Country(name: "Liberia", code: "+231", flag: "🇱🇷", maxLength: 7),
  Country(name: "Libya", code: "+218", flag: "🇱🇾", maxLength: 9),
  Country(name: "Liechtenstein", code: "+423", flag: "🇱🇮", maxLength: 7),
  Country(name: "Lithuania", code: "+370", flag: "🇱🇹", maxLength: 8),
  Country(name: "Luxembourg", code: "+352", flag: "🇱🇺", maxLength: 9),
  Country(name: "Madagascar", code: "+261", flag: "🇲🇬", maxLength: 9),
  Country(name: "Malawi", code: "+265", flag: "🇲🇼", maxLength: 9),
  Country(name: "Malaysia", code: "+60", flag: "🇲🇾", maxLength: 9),
  Country(name: "Maldives", code: "+960", flag: "🇲🇻", maxLength: 7),
  Country(name: "Mali", code: "+223", flag: "🇲🇱", maxLength: 8),
  Country(name: "Malta", code: "+356", flag: "🇲🇹", maxLength: 8),
  Country(name: "Marshall Islands", code: "+692", flag: "🇲🇭", maxLength: 7),
  Country(name: "Mauritania", code: "+222", flag: "🇲🇷", maxLength: 8),
  Country(name: "Mauritius", code: "+230", flag: "🇲🇺", maxLength: 8),
  Country(name: "Mexico", code: "+52", flag: "🇲🇽", maxLength: 10),
  Country(name: "Micronesia", code: "+691", flag: "🇫🇲", maxLength: 7),
  Country(name: "Moldova", code: "+373", flag: "🇲🇩", maxLength: 8),
  Country(name: "Monaco", code: "+377", flag: "🇲🇨", maxLength: 8),
  Country(name: "Mongolia", code: "+976", flag: "🇲🇳", maxLength: 8),
  Country(name: "Montenegro", code: "+382", flag: "🇲🇪", maxLength: 8),
  Country(name: "Morocco", code: "+212", flag: "🇲🇦", maxLength: 9),
  Country(name: "Mozambique", code: "+258", flag: "🇲🇿", maxLength: 9),
  Country(name: "Myanmar", code: "+95", flag: "🇲🇲", maxLength: 9),
  Country(name: "Namibia", code: "+264", flag: "🇳🇦", maxLength: 9),
  Country(name: "Nauru", code: "+674", flag: "🇳🇷", maxLength: 7),
  Country(name: "Nepal", code: "+977", flag: "🇳🇵", maxLength: 10),
  Country(name: "Netherlands", code: "+31", flag: "🇳🇱", maxLength: 9),
  Country(name: "New Zealand", code: "+64", flag: "🇳🇿", maxLength: 8),
  Country(name: "Nicaragua", code: "+505", flag: "🇳🇮", maxLength: 8),
  Country(name: "Niger", code: "+227", flag: "🇳🇪", maxLength: 8),
  Country(name: "Nigeria", code: "+234", flag: "🇳🇬", maxLength: 10),
  Country(name: "North Korea", code: "+850", flag: "🇰🇵", maxLength: 10),
  Country(name: "North Macedonia", code: "+389", flag: "🇲🇰", maxLength: 8),
  Country(name: "Norway", code: "+47", flag: "🇳🇴", maxLength: 8),
  Country(name: "Oman", code: "+968", flag: "🇴🇲", maxLength: 8),
  Country(name: "Pakistan", code: "+92", flag: "🇵🇰", maxLength: 10),
  Country(name: "Palau", code: "+680", flag: "🇵🇼", maxLength: 7),
  Country(name: "Palestine", code: "+970", flag: "🇵🇸", maxLength: 9),
  Country(name: "Panama", code: "+507", flag: "🇵🇦", maxLength: 8),
  Country(name: "Papua New Guinea", code: "+675", flag: "🇵🇬", maxLength: 8),
  Country(name: "Paraguay", code: "+595", flag: "🇵🇾", maxLength: 9),
  Country(name: "Peru", code: "+51", flag: "🇵🇪", maxLength: 9),
  Country(name: "Philippines", code: "+63", flag: "🇵🇭", maxLength: 10),
  Country(name: "Poland", code: "+48", flag: "🇵🇱", maxLength: 9),
  Country(name: "Portugal", code: "+351", flag: "🇵🇹", maxLength: 9),
  Country(name: "Qatar", code: "+974", flag: "🇶🇦", maxLength: 8),
  Country(name: "Romania", code: "+40", flag: "🇷🇴", maxLength: 10),
  Country(name: "Russia", code: "+7", flag: "🇷🇺", maxLength: 10),
  Country(name: "Rwanda", code: "+250", flag: "🇷🇼", maxLength: 9),
  Country(name: "Saint Kitts and Nevis", code: "+1-869", flag: "🇰🇳", maxLength: 7),
  Country(name: "Saint Lucia", code: "+1-758", flag: "🇱🇨", maxLength: 7),
  Country(name: "Saint Vincent and the Grenadines", code: "+1-784", flag: "🇻🇨", maxLength: 7),
  Country(name: "Samoa", code: "+685", flag: "🇼🇸", maxLength: 7),
  Country(name: "San Marino", code: "+378", flag: "🇸🇲", maxLength: 10),
  Country(name: "Sao Tome and Principe", code: "+239", flag: "🇸🇹", maxLength: 7),
  Country(name: "Saudi Arabia", code: "+966", flag: "🇸🇦", maxLength: 9),
  Country(name: "Senegal", code: "+221", flag: "🇸🇳", maxLength: 9),
  Country(name: "Serbia", code: "+381", flag: "🇷🇸", maxLength: 9),
  Country(name: "Seychelles", code: "+248", flag: "🇸🇨", maxLength: 7),
  Country(name: "Sierra Leone", code: "+232", flag: "🇸🇱", maxLength: 8),
  Country(name: "Singapore", code: "+65", flag: "🇸🇬", maxLength: 8),
  Country(name: "Slovakia", code: "+421", flag: "🇸🇰", maxLength: 9),
  Country(name: "Slovenia", code: "+386", flag: "🇸🇮", maxLength: 8),
  Country(name: "Solomon Islands", code: "+677", flag: "🇸🇧", maxLength: 7),
  Country(name: "Somalia", code: "+252", flag: "🇸🇴", maxLength: 9),
  Country(name: "South Africa", code: "+27", flag: "🇿🇦", maxLength: 9),
  Country(name: "South Korea", code: "+82", flag: "🇰🇷", maxLength: 10),
  Country(name: "South Sudan", code: "+211", flag: "🇸🇸", maxLength: 9),
  Country(name: "Spain", code: "+34", flag: "🇪🇸", maxLength: 9),
  Country(name: "Sri Lanka", code: "+94", flag: "🇱🇰", maxLength: 9),
  Country(name: "Sudan", code: "+249", flag: "🇸🇩", maxLength: 9),
  Country(name: "Suriname", code: "+597", flag: "🇸🇷", maxLength: 7),
  Country(name: "Swaziland", code: "+268", flag: "🇸🇿", maxLength: 7),
  Country(name: "Sweden", code: "+46", flag: "🇸🇪", maxLength: 10),
  Country(name: "Switzerland", code: "+41", flag: "🇨🇭", maxLength: 9),
  Country(name: "Syria", code: "+963", flag: "🇸🇾", maxLength: 9),
  Country(name: "Taiwan", code: "+886", flag: "🇹🇼", maxLength: 9),
  Country(name: "Tajikistan", code: "+992", flag: "🇹🇯", maxLength: 9),
  Country(name: "Tanzania", code: "+255", flag: "🇹🇿", maxLength: 9),
  Country(name: "Thailand", code: "+66", flag: "🇹🇭", maxLength: 9),
  Country(name: "Timor-Leste", code: "+670", flag: "🇹🇱", maxLength: 7),
  Country(name: "Togo", code: "+228", flag: "🇹🇬", maxLength: 8),
  Country(name: "Tonga", code: "+676", flag: "🇹🇴", maxLength: 5),
  Country(name: "Trinidad and Tobago", code: "+1-868", flag: "🇹🇹", maxLength: 7),
  Country(name: "Tunisia", code: "+216", flag: "🇹🇳", maxLength: 8),
  Country(name: "Turkey", code: "+90", flag: "🇹🇷", maxLength: 10),
  Country(name: "Turkmenistan", code: "+993", flag: "🇹🇲", maxLength: 8),
  Country(name: "Tuvalu", code: "+688", flag: "🇹🇻", maxLength: 5),
  Country(name: "Uganda", code: "+256", flag: "🇺🇬", maxLength: 9),
  Country(name: "Ukraine", code: "+380", flag: "🇺🇦", maxLength: 9),
  Country(name: "United Arab Emirates", code: "+971", flag: "🇦🇪", maxLength: 9),
  Country(name: "United Kingdom", code: "+44", flag: "🇬🇧", maxLength: 10),
  Country(name: "United States", code: "+1", flag: "🇺🇸", maxLength: 10),
  Country(name: "Uruguay", code: "+598", flag: "🇺🇾", maxLength: 8),
  Country(name: "Uzbekistan", code: "+998", flag: "🇺🇿", maxLength: 9),
  Country(name: "Vanuatu", code: "+678", flag: "🇻🇺", maxLength: 7),
  Country(name: "Vatican City", code: "+379", flag: "🇻🇦", maxLength: 10),
  Country(name: "Venezuela", code: "+58", flag: "🇻🇪", maxLength: 10),
  Country(name: "Vietnam", code: "+84", flag: "🇻🇳", maxLength: 9),
  Country(name: "Yemen", code: "+967", flag: "🇾🇪", maxLength: 9),
  Country(name: "Zambia", code: "+260", flag: "🇿🇲", maxLength: 9),
  Country(name: "Zimbabwe", code: "+263", flag: "🇿🇼", maxLength: 9),
];
